name: Feature Request
description: What Feature do you want to request? DO NOT RQUEST NEW CHARACTERS TO BE IN HERE.
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on the **base** engine?
    validations:
      required: true
  - type: dropdown
    id: eyetest
    attributes:
      label: To test your sight, and reliability, please select the option of what should NOT be requested.
      options:
        - Proper credit that was forgotten
        - Thing that would not cause problems
        - Useful feature
        - Full Calculator Functionality
        - Actual feedback
        - A good idea
        - Winning icons
        - Better LUA mod support idea
        - Code optimization that would make the game faster. (You should make a PR if this is your request, by the way.)
    validations:
      required: true
